// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAue-7mgFM5_zNP_xs-fsroEi36hRMNTH4',
    appId: '1:412126122862:web:dd9ca0bdd6e3dc48e2a77f',
    messagingSenderId: '412126122862',
    projectId: 'emival-engenharia-inventario',
    authDomain: 'emival-engenharia-inventario.firebaseapp.com',
    storageBucket: 'emival-engenharia-inventario.appspot.com',
    measurementId: 'G-KZ09SH12K6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaZi0MWXlF4HdD7EIzWDsW3w1enzq3VDw',
    appId: '1:412126122862:android:b5dafabb424c99e4e2a77f',
    messagingSenderId: '412126122862',
    projectId: 'emival-engenharia-inventario',
    storageBucket: 'emival-engenharia-inventario.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPxGlpsy93mBfU7Fu_N1XCN1xYQgt0bco',
    appId: '1:412126122862:ios:63d83c42af84ca7ae2a77f',
    messagingSenderId: '412126122862',
    projectId: 'emival-engenharia-inventario',
    storageBucket: 'emival-engenharia-inventario.appspot.com',
    iosClientId: '412126122862-5evk880r6o2hv8275n3revoiekuo12tk.apps.googleusercontent.com',
    iosBundleId: 'br.com.yellowtreesoftware.emivalInventario',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPxGlpsy93mBfU7Fu_N1XCN1xYQgt0bco',
    appId: '1:412126122862:ios:63d83c42af84ca7ae2a77f',
    messagingSenderId: '412126122862',
    projectId: 'emival-engenharia-inventario',
    storageBucket: 'emival-engenharia-inventario.appspot.com',
    iosClientId: '412126122862-5evk880r6o2hv8275n3revoiekuo12tk.apps.googleusercontent.com',
    iosBundleId: 'br.com.yellowtreesoftware.emivalInventario',
  );
}
